### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by vladisslave** [vladisslave/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ViacheslavUkraintsev** [comment]
<h2>Résumé</h2>
                  <p>A brilliant, gorgeous, extravagant, intelligent, versatile, stunning, stylish, creative, perfect, incomparable, charming, attractive, mind-blowing, amazing, handsome and sophisticated historian, political writer, journalist, theater director, television host, actor and singer. I am the author of The First Scientific History of the War of 1812</p>
